qiniucloud:
  accesskey: iMOdZ21AUiVfWotTH65n1GjqjlMzbH1HKVzbtyDN
  secretkey: Fyqug5fz9t5pmJXjAAEyhy88QW6pq0tnUZEHxF3O
  hostsname: http://rylosd94d.hn-bkt.clouddn.com/
  bucketnaem: gxy-blog
es:
  host: http://192.168.171.168:9200
server:
  port: 8089
spring:
  rabbitmq:
    host: 192.168.150.101 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: itcast # 用户名
    password: 123321 # 密码
  #邮箱验证
  mail:
    host: smtp.163.com
    username: gxy513822200101@163.com
    password: NOQJPFJWTLVTENSM
    default-encoding: utf-8
  application:
    name: Blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gxy-blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '010104'
  redis:
    host: localhost
    port: 6379
    #    password: 010104
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.blog.gxyblog.entity # 别名扫描包

logging:
  level:
    com.hmdp: debug


